source_language: "en"

preserve_hierarchy: true
base_path: "."

ignore:
  - ".github/**"
  - ".idea/**"
  - "node_modules/**"
  - "translated/**"

files:
  - source: "launcher/**/*.resx"
    translation: "translated/%original_path%/%file_name%.%locale%.%file_extension%"
    export_options:
      skip_untranslated_strings: true
      skip_untranslated_files: true

  # - source: "genshin-stella-mod/**/*.resx"
  #   translation: "translated/%original_path%/%file_name%.%locale%.%file_extension%"
  #   export_options:
  #     skip_untranslated_strings: true
  #     skip_untranslated_files: true

  - source: "prepare-stella/**/*.resx"
    translation: "translated/%original_path%/%file_name%.%locale%.%file_extension%"
    export_options:
      skip_untranslated_strings: true
      skip_untranslated_files: true

  - source: "configuration-window/**/*.resx"
    translation: "translated/%original_path%/%file_name%.%locale%.%file_extension%"
    export_options:
      skip_untranslated_strings: true
      skip_untranslated_files: true

  - source: "info-before-start/**/*.resx"
    translation: "translated/%original_path%/%file_name%.%locale%.%file_extension%"
    export_options:
      skip_untranslated_strings: true
      skip_untranslated_files: true

  - source: "fps-unlocker/**/*.resx"
    translation: "translated/%original_path%/%file_name%.%locale%.%file_extension%"
    export_options:
      skip_untranslated_strings: true
      skip_untranslated_files: true

  - source: "website/**/*.js"
    translation: "translated/%original_path%/%file_name%.%locale%.%file_extension%"
    export_options:
      skip_untranslated_strings: true
      skip_untranslated_files: true
