source_language: "en"

files:
  - source: "/launcher/Forms/**/*.resx"
    translation: "/translated/launcher/Forms/%original_path%/%original_file_name%.%two_letters_code%.resx"

  - source: "/launcher/Properties/Resources.resx"
    translation: "/translated/launcher/Properties/Resources.%two_letters_code%.resx"

  - source: "/website/*.js"
    translation: "/website/%two_letters_code%.js"

  - source: "/website/missing-translations/en.js"
    translation: "/website/missing-translations/%two_letters_code%.js"
