source_language: "en"

base_path: "."
preserve_hierarchy: true

files:
  - source: "launcher/**/*.resx"
    translation: "translated/%original_path%/%file_name%.%locale%.%file_extension%"
    skip_untranslated_strings: true
    skip_untranslated_files: true
    ignore:
      - "translated/**"

  # - source: "genshin-stella-mod/**/*.resx"
  #   translation: "translated/%original_path%/%file_name%.%locale%.%file_extension%"
  #   skip_untranslated_strings: true
  #   skip_untranslated_files: true
  #   ignore:
  #     - "translated/**"

  - source: "prepare-stella/**/*.resx"
    translation: "translated/%original_path%/%file_name%.%locale%.%file_extension%"
    skip_untranslated_strings: true
    skip_untranslated_files: true
    ignore:
      - "translated/**"

  - source: "configuration-window/**/*.resx"
    translation: "translated/%original_path%/%file_name%.%locale%.%file_extension%"
    skip_untranslated_strings: true
    skip_untranslated_files: true
    ignore:
      - "translated/**"

  - source: "info-before-start/**/*.resx"
    translation: "translated/%original_path%/%file_name%.%locale%.%file_extension%"
    skip_untranslated_strings: true
    skip_untranslated_files: true
    ignore:
      - "translated/**"

  - source: "fps-unlocker/**/*.resx"
    translation: "translated/%original_path%/%file_name%.%locale%.%file_extension%"
    skip_untranslated_strings: true
    skip_untranslated_files: true
    ignore:
      - "translated/**"

  - source: "website/**/*.js"
    translation: "translated/%original_path%/%file_name%.%two_letters_code%.%file_extension%"
    skip_untranslated_strings: true
    skip_untranslated_files: true
    ignore:
      - "translated/**"
